// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyixtkylxcctkahequin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aXh0a3lseGNjdGthaGVxdWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDkyMDQsImV4cCI6MjA2MjA4NTIwNH0.8jKopKrbjo_A_j4ewi6l6VWqImp7tfVyUZfasfvmUms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);